/**
 * City Power BOQ Data
 *
 * This file contains the exhaustive list of BOQ items for City Power.
 * Each item has:
 * - sapNumber: string (SAP #)
 * - shortDescription: string
 * - unit: string (e.g., M3, M2, EA, HR)
 * - rate: string (decimal as string, e.g., "126.63")
 * - category: string (optional, for grouping)
 */

export const cityPowerBoqItems = [
  // Main BOQ Items (10-4050)
  {
    sapNumber: "10",
    shortDescription: "Soil dig, backfill, comp hand pickable",
    unit: "M3",
    rate: "126.63",
  },
  {
    sapNumber: "20",
    shortDescription: "Soil machine excavate dig, backfill, complete",
    unit: "M3",
    rate: "143.35",
  },
  {
    sapNumber: "30",
    shortDescription: "Lose rocks/boulders soil, dig, backfill, complete",
    unit: "M3",
    rate: "173.98",
  },
  {
    sapNumber: "40",
    shortDescription: "Lose rocks/boulders, soil mac, backfill, complete",
    unit: "M3",
    rate: "212.85",
  },
  {
    sapNumber: "50",
    shortDescription: "Rock wedge & power drill",
    unit: "M3",
    rate: "338.6",
  },
  {
    sapNumber: "60",
    shortDescription: "Pole hole removal of rock",
    unit: "M3",
    rate: "294.96",
  },
  {
    sapNumber: "70",
    shortDescription: "Rock requiring blasting",
    unit: "M3",
    rate: "297.91",
  },
  {
    sapNumber: "80",
    shortDescription: "Tar paving cut,& remove",
    unit: "M2",
    rate: "252.79",
  },
  {
    sapNumber: "90",
    shortDescription: "Concrete 100mm thick cut & remove",
    unit: "M2",
    rate: "170.57",
  },
  {
    sapNumber: "100",
    shortDescription: "Interlock blocks lift & stack (retaining)",
    unit: "M2",
    rate: "84.17",
  },
  {
    sapNumber: "110",
    shortDescription: "Lifting & stacking of paving bricks",
    unit: "M2",
    rate: "71.11",
  },
  {
    sapNumber: "120",
    shortDescription: "Concrete slabs lifting & stacking",
    unit: "M2",
    rate: "110.94",
  },
  {
    sapNumber: "130",
    shortDescription: "Lift & stack preservation of lawn grass",
    unit: "M2",
    rate: "88.45",
  },
  {
    sapNumber: "140",
    shortDescription: "Reinstate used inter lock blocks",
    unit: "M2",
    rate: "135.76",
  },
  {
    sapNumber: "150",
    shortDescription: "Supply and install new inter lock blocks",
    unit: "M2",
    rate: "219.73",
  },
  {
    sapNumber: "160",
    shortDescription: "Reinstate used concrete slabs",
    unit: "M2",
    rate: "143.92",
  },
  {
    sapNumber: "170",
    shortDescription: "Supply and install new concrete slabs",
    unit: "M2",
    rate: "241.24",
  },
  {
    sapNumber: "180",
    shortDescription: "Reinstate used paving bricks",
    unit: "M2",
    rate: "116.28",
  },
  {
    sapNumber: "190",
    shortDescription: "Supply and install new paving bricks",
    unit: "M2",
    rate: "204.64",
  },
  {
    sapNumber: "200",
    shortDescription: "Backfill trench & compact only",
    unit: "M2",
    rate: "89.47",
  },
  {
    sapNumber: "210",
    shortDescription: "Supply dry clean river sand",
    unit: "M3",
    rate: "208.5",
  },
  {
    sapNumber: "220",
    shortDescription: "Supply acceptable filling soil",
    unit: "M3",
    rate: "159.26",
  },
  {
    sapNumber: "230",
    shortDescription: "Reinstate lawn",
    unit: "M2",
    rate: "70.25",
  },
  {
    sapNumber: "240",
    shortDescription: "Supply and install new lawn",
    unit: "M2",
    rate: "84.63",
  },
  {
    sapNumber: "250",
    shortDescription: "Supply and install new tar",
    unit: "M2",
    rate: "518.38",
  },
  {
    sapNumber: "260",
    shortDescription: "Supply and cast ready mix concrete",
    unit: "M3",
    rate: "596.97",
  },
  {
    sapNumber: "270",
    shortDescription: "Supply and cast concrete (self mix)",
    unit: "M2",
    rate: "927.14",
  },
  {
    sapNumber: "280",
    shortDescription: "Trench on concrete road",
    unit: "M3",
    rate: "315.63",
  },
  {
    sapNumber: "290",
    shortDescription: "Disposal of rock from excavations",
    unit: "M3",
    rate: "221.71",
  },
  {
    sapNumber: "300",
    shortDescription: "Rock, rubble and spoil removal & disposal",
    unit: "M3",
    rate: "501.34",
  },
  {
    sapNumber: "310",
    shortDescription: "Rubble and spoil removal & disposal",
    unit: "M3",
    rate: "546.17",
  },
  {
    sapNumber: "320",
    shortDescription: "Create temporary walkway over trench",
    unit: "EA",
    rate: "1233.66",
  },
  {
    sapNumber: "330",
    shortDescription: "Sign boards JRA cop for projects only",
    unit: "EA",
    rate: "936.54",
  },
  {
    sapNumber: "340",
    shortDescription: "Obtain way leave information",
    unit: "EA",
    rate: "899.96",
  },
  {
    sapNumber: "350",
    shortDescription: "Install Danger barriers for trenches",
    unit: "EA",
    rate: "870.03",
  },
  {
    sapNumber: "360",
    shortDescription: "Shoring of trench walls (for 1,5m plus only)",
    unit: "M3",
    rate: "482.09",
  },
  {
    sapNumber: "370",
    shortDescription: "Pumping out flooded trench",
    unit: "EA",
    rate: "504.82",
  },
  {
    sapNumber: "380",
    shortDescription:
      "Location of services with the use of appropriate locator",
    unit: "EA",
    rate: "1053.45",
  },
  {
    sapNumber: "390",
    shortDescription: "LV cable fault location",
    unit: "EA",
    rate: "1078.93",
  },
  {
    sapNumber: "400",
    shortDescription: "MV Cable fault location",
    unit: "EA",
    rate: "1278.71",
  },
  {
    sapNumber: "410",
    shortDescription: "Traffic deviation (where applicable)",
    unit: "EA",
    rate: "84.66",
  },
  {
    sapNumber: "420",
    shortDescription: "Laying of 300mm x3 MV 3 core cable",
    unit: "M",
    rate: "88.43",
  },
  {
    sapNumber: "430",
    shortDescription: "Laying of 185mm x3 MV 3 core cable",
    unit: "M",
    rate: "70.64",
  },
  {
    sapNumber: "440",
    shortDescription: "Laying of 95mm x3 MV 3 core cable",
    unit: "M",
    rate: "51.73",
  },
  {
    sapNumber: "450",
    shortDescription: "Laying of 20 pair control cable",
    unit: "M",
    rate: "45.77",
  },
  {
    sapNumber: "460",
    shortDescription: "Laying of LV 4 core cable 300mm2",
    unit: "M",
    rate: "68.66",
  },
  {
    sapNumber: "470",
    shortDescription: "Laying of LV 4 core cable 70 to185mm2",
    unit: "M",
    rate: "45.91",
  },
  {
    sapNumber: "480",
    shortDescription: "Laying of LV 4 core cable 25 to 35mm2",
    unit: "M",
    rate: "91.21",
  },
  {
    sapNumber: "490",
    shortDescription: "Install cable in tunnels 300mm2 3 core",
    unit: "M",
    rate: "131.74",
  },
  {
    sapNumber: "500",
    shortDescription: "Install cable in tunnels 185mm2 3 core",
    unit: "M",
    rate: "100.72",
  },
  {
    sapNumber: "510",
    shortDescription: "Install cable in tunnels 630mm2 1 core",
    unit: "M",
    rate: "155.63",
  },
  {
    sapNumber: "520",
    shortDescription: "Install cable in tunnels hard drawn bare copper",
    unit: "M",
    rate: "91.22",
  },
  {
    sapNumber: "530",
    shortDescription: "Laying of LV cable 16mm2",
    unit: "M",
    rate: "49.34",
  },
  {
    sapNumber: "540",
    shortDescription: "Laying plastic marker tape",
    unit: "M",
    rate: "13.37",
  },
  {
    sapNumber: "550",
    shortDescription: "Installation of sleeves 110 mm",
    unit: "M",
    rate: "32.11",
  },
  {
    sapNumber: "560",
    shortDescription: "Installation of sleeves 160mm",
    unit: "M",
    rate: "39.65",
  },
  {
    sapNumber: "570",
    shortDescription: "Supply and install 110mm steel pipe",
    unit: "M",
    rate: "104.84",
  },
  {
    sapNumber: "580",
    shortDescription: "Drawn cable = >95 mm2 through pipe",
    unit: "M",
    rate: "509.65",
  },
  {
    sapNumber: "590",
    shortDescription: "Drawn cable < 95 mm2 through pipe",
    unit: "M",
    rate: "81.98",
  },
  {
    sapNumber: "600",
    shortDescription: "Drawn LV pilot cable<35 mm2 through pipe",
    unit: "M",
    rate: "27.49",
  },
  {
    sapNumber: "610",
    shortDescription: "MV Joint for 300mm2 x 3 core cable",
    unit: "EA",
    rate: "1074.96",
  },
  {
    sapNumber: "620",
    shortDescription: "MV Joint for 185mm2 x 3 core cable",
    unit: "EA",
    rate: "960.83",
  },
  {
    sapNumber: "630",
    shortDescription: "MV Joint for 95mm2 x 3 core cable",
    unit: "EA",
    rate: "850.64",
  },
  {
    sapNumber: "640",
    shortDescription: "LV Joint for 300mm2 x 4 core cable",
    unit: "EA",
    rate: "918.94",
  },
  {
    sapNumber: "650",
    shortDescription: "LV Joint for 70 to 185mm2 x4 core cable",
    unit: "EA",
    rate: "747.97",
  },
  {
    sapNumber: "660",
    shortDescription: "LV Joint for 25mm2 & 35mm2 x4 core cable",
    unit: "EA",
    rate: "437.39",
  },
  {
    sapNumber: "670",
    shortDescription: "LV Joint for 16mm2 >=2 core or more cable",
    unit: "EA",
    rate: "345.66",
  },
  {
    sapNumber: "680",
    shortDescription: "MV make-off & termination >= 300mm2 x 3 core",
    unit: "EA",
    rate: "893.75",
  },
  {
    sapNumber: "690",
    shortDescription: "MV make-off & termination >= 185mm2 x 3 core",
    unit: "EA",
    rate: "788.62",
  },
  {
    sapNumber: "700",
    shortDescription: "MV make-off & termination >= 95mm2 x 3 core",
    unit: "EA",
    rate: "622.88",
  },
  {
    sapNumber: "710",
    shortDescription: "LV make-off & termination 300mm2 4 Core",
    unit: "ea",
    rate: "631.89",
  },
  {
    sapNumber: "720",
    shortDescription: "LV make-off & termination 70mm2 to 185mm2 x 4 core",
    unit: "EA",
    rate: "476.15",
  },
  {
    sapNumber: "730",
    shortDescription: "LV make-off & termination >= 25mm2 & 35mm2 x 4 core",
    unit: "EA",
    rate: "341.25",
  },
  {
    sapNumber: "740",
    shortDescription: "LV make-off & termination 16 mm2 >= 2 core",
    unit: "EA",
    rate: "215.37",
  },
  {
    sapNumber: "750",
    shortDescription: "Seal LV/MV cable ends",
    unit: "EA",
    rate: "106.5",
  },
  {
    sapNumber: "760",
    shortDescription: "Earth MVC & MSS install earths including excavation",
    unit: "EA",
    rate: "1262.64",
  },
  {
    sapNumber: "770",
    shortDescription: "Install earth spike & connect including CAD welding",
    unit: "EA",
    rate: "303.47",
  },
  {
    sapNumber: "780",
    shortDescription: "Supply & install earth spike",
    unit: "EA",
    rate: "212.15",
  },
  {
    sapNumber: "790",
    shortDescription: "Repair earth mats",
    unit: "EA",
    rate: "384.68",
  },
  {
    sapNumber: "800",
    shortDescription: "Positioning of MSS (excluding cable & MV switchgear)",
    unit: "EA",
    rate: "1576.32",
  },
  {
    sapNumber: "810",
    shortDescription: "Install pole mounted distributor transformer",
    unit: "EA",
    rate: "1459.32",
  },
  {
    sapNumber: "820",
    shortDescription: "Complete install of TSS",
    unit: "EA",
    rate: "3404.47",
  },
  {
    sapNumber: "830",
    shortDescription: "Position MV transformers",
    unit: "EA",
    rate: "834.23",
  },
  {
    sapNumber: "840",
    shortDescription: "Position MV switchgear RMU",
    unit: "EA",
    rate: "778.14",
  },
  {
    sapNumber: "850",
    shortDescription: "Position MV meter cubicle",
    unit: "EA",
    rate: "607.93",
  },
  {
    sapNumber: "860",
    shortDescription: "Installation of MV VCB + meter cubicle (BMK)",
    unit: "EA",
    rate: "828.03",
  },
  {
    sapNumber: "870",
    shortDescription: "Install MV VCB cubicle units",
    unit: "EA",
    rate: "642.59",
  },
  {
    sapNumber: "880",
    shortDescription: "Cement top ducts Supply, installl WxL",
    unit: "M2",
    rate: "295.82",
  },
  {
    sapNumber: "890",
    shortDescription: "Sign write complete MV sub",
    unit: "EA",
    rate: "275.28",
  },
  {
    sapNumber: "900",
    shortDescription: "Install designation labels' (RMU & mini-subs)",
    unit: "EA",
    rate: "209.59",
  },
  {
    sapNumber: "910",
    shortDescription:
      "Disconnect, reconnect & test LV Termination (excluding LV tape)",
    unit: "EA",
    rate: "192.25",
  },
  {
    sapNumber: "920",
    shortDescription:
      "Disconnect, reconnect & test excluding MV taped termination",
    unit: "EA",
    rate: "231.7",
  },
  {
    sapNumber: "930",
    shortDescription: "Install chamber light wiring",
    unit: "EA",
    rate: "367.23",
  },
  {
    sapNumber: "940",
    shortDescription: "Installation maximum demand meter",
    unit: "EA",
    rate: "226.29",
  },
  {
    sapNumber: "950",
    shortDescription: "Installation & connecting of kW/h meter",
    unit: "EA",
    rate: "353.84",
  },
  {
    sapNumber: "960",
    shortDescription: "Installation of test block and fuses",
    unit: "EA",
    rate: "222.23",
  },
  {
    sapNumber: "970",
    shortDescription: "Connect test block and fuses",
    unit: "EA",
    rate: "209.32",
  },
  {
    sapNumber: "980",
    shortDescription:
      "Install, connect 3 phase kW/h meter & 80A mcb & <25mm2 cable",
    unit: "EA",
    rate: "515.4",
  },
  {
    sapNumber: "990",
    shortDescription:
      "Install, connect 3 phase kW/h meter & 80A mcb & <40m cable",
    unit: "EA",
    rate: "695.55",
  },
  {
    sapNumber: "1000",
    shortDescription:
      "Install, connect 1 phase kW/h meter & 80A mcb & <25mm2 cable",
    unit: "EA",
    rate: "368.82",
  },
  {
    sapNumber: "1010",
    shortDescription:
      "Install, connect 1 phase kW/h meter & 80A mcb & <40m cable",
    unit: "EA",
    rate: "531.14",
  },
  {
    sapNumber: "1020",
    shortDescription: "500 v megger test between cores and core",
    unit: "EA",
    rate: "149.01",
  },
  {
    sapNumber: "1030",
    shortDescription: "Earth line loop impedance test per circuit",
    unit: "EA",
    rate: "111.37",
  },
  {
    sapNumber: "1040",
    shortDescription:
      "Fit main Circuit Breaker to MSS or LV distribution board",
    unit: "EA",
    rate: "396.67",
  },
  {
    sapNumber: "1050",
    shortDescription: "Fit add main isolator to LV distribution Board",
    unit: "EA",
    rate: "348.77",
  },
  {
    sapNumber: "1060",
    shortDescription: "Install LV distribution board",
    unit: "EA",
    rate: "617.64",
  },
  {
    sapNumber: "1070",
    shortDescription: "Install LV Distribution Board fuse",
    unit: "EA",
    rate: "477.16",
  },
  {
    sapNumber: "1080",
    shortDescription: "Fit additional fuse",
    unit: "EA",
    rate: "266.78",
  },
  {
    sapNumber: "1090",
    shortDescription: "Replace LV fuse",
    unit: "EA",
    rate: "136.21",
  },
  {
    sapNumber: "1100",
    shortDescription: "Replace LV fuse & carriage",
    unit: "EA",
    rate: "153.92",
  },
  {
    sapNumber: "1110",
    shortDescription: "Install LV Pillar Box ( Fibre) & Base",
    unit: "EA",
    rate: "460.79",
  },
  {
    sapNumber: "1120",
    shortDescription: "Install LV Distribution Board (steel) & plinth",
    unit: "EA",
    rate: "475.52",
  },
  {
    sapNumber: "1130",
    shortDescription:
      "Installation & connection Main Circuit Breaker in Distribution Board",
    unit: "EA",
    rate: "285.82",
  },
  {
    sapNumber: "1140",
    shortDescription: "Replace existing low voltage 1 phase circuit breaker",
    unit: "EA",
    rate: "208.23",
  },
  {
    sapNumber: "1150",
    shortDescription: "Replace existing low voltage 3 phase circuit breaker",
    unit: "EA",
    rate: "227.08",
  },
  {
    sapNumber: "1160",
    shortDescription: "Reset LV MCB",
    unit: "EA",
    rate: "110.63",
  },
  {
    sapNumber: "1170",
    shortDescription: "Repair loose connection",
    unit: "EA",
    rate: "76.88",
  },
  {
    sapNumber: "1180",
    shortDescription: "Replace jumpers",
    unit: "EA",
    rate: "189.88",
  },
  {
    sapNumber: "1190",
    shortDescription: "Jumper between switch gear and transformer LV/MV",
    unit: "EA",
    rate: "245.49",
  },
  {
    sapNumber: "1200",
    shortDescription: "Redundancy cable out open trench, remove",
    unit: "M",
    rate: "43.57",
  },
  {
    sapNumber: "1210",
    shortDescription:
      "Decommission redundant Bare OHL conductor & removal & offload",
    unit: "M",
    rate: "75.49",
  },
  {
    sapNumber: "1220",
    shortDescription: "Decommission redundant pole remove, load and transfer",
    unit: "EA",
    rate: "490.51",
  },
  {
    sapNumber: "1230",
    shortDescription:
      "Decommission redundant MV switchgear, remove, load and transfer",
    unit: "EA",
    rate: "1646.36",
  },
  {
    sapNumber: "1240",
    shortDescription: "Decommission redundant MSS, remove, load and transfer",
    unit: "EA",
    rate: "2887.1",
  },
  {
    sapNumber: "1250",
    shortDescription:
      "Decommission redundant transformer, remove, load, transfer",
    unit: "EA",
    rate: "2220.6",
  },
  {
    sapNumber: "1260",
    shortDescription:
      "Decommission redundant pole transformer remove, load and transfer",
    unit: "EA",
    rate: "1851.64",
  },
  {
    sapNumber: "1270",
    shortDescription: "Cleaning vegetation & rubble in TSS Servitutes",
    unit: "M2",
    rate: "71.79",
  },
  {
    sapNumber: "1280",
    shortDescription: "straightening of skew poles",
    unit: "M2",
    rate: "93.73",
  },
  {
    sapNumber: "1290",
    shortDescription: "First line inspection of load centres",
    unit: "EA",
    rate: "240.3",
  },
  {
    sapNumber: "1300",
    shortDescription: "Maintaining Load centre Transformer ( Including O",
    unit: "EA",
    rate: "3659.78",
  },
  {
    sapNumber: "1310",
    shortDescription: "Maintaining Load centre MV Switchgear",
    unit: "EA",
    rate: "3729.61",
  },
  {
    sapNumber: "1320",
    shortDescription: "Maintaining Load centre LV Switch gear ( Including K",
    unit: "EA",
    rate: "2468.93",
  },
  {
    sapNumber: "1330",
    shortDescription: "Maintaining Load centre S/I control pa",
    unit: "EA",
    rate: "1365.79",
  },
  {
    sapNumber: "1340",
    shortDescription: "Prime cost sum for community liaison off",
    unit: "EA",
    rate: "9500",
  },
  {
    sapNumber: "1350",
    shortDescription: "Prime cost sum for special materials",
    unit: "EA",
    rate: "36205.67",
  },
  {
    sapNumber: "1360",
    shortDescription: "Establishment of site camp",
    unit: "EA",
    rate: "12791.82",
  },
  {
    sapNumber: "1370",
    shortDescription: "Transporting of 8/10.5 fibre glass poles",
    unit: "EA",
    rate: "455.29",
  },
  {
    sapNumber: "1380",
    shortDescription: "Transport steel/wood 5/7.2/9.2/11.5m st",
    unit: "EA",
    rate: "406.77",
  },
  {
    sapNumber: "1390",
    shortDescription: "Transport Steel double arm curved spig",
    unit: "EA",
    rate: "378.82",
  },
  {
    sapNumber: "1400",
    shortDescription: "Transport steel 17m straight pole",
    unit: "EA",
    rate: "550.38",
  },
  {
    sapNumber: "1410",
    shortDescription: "Transport concrete 7 to 7,5 metre pole",
    unit: "EA",
    rate: "481.74",
  },
  {
    sapNumber: "1420",
    shortDescription: "Transport concrete 9 to 9,3 metre pole",
    unit: "EA",
    rate: "514.11",
  },
  {
    sapNumber: "1430",
    shortDescription: "Transport concrete 10 to 11 metre pole",
    unit: "EA",
    rate: "613.2",
  },
  {
    sapNumber: "1440",
    shortDescription: "Install 11.5 D-Curved pole, lmr & Lamp",
    unit: "EA",
    rate: "470.99",
  },
  {
    sapNumber: "1450",
    shortDescription: "Install 11.5m Curved pole, lmr & Lamp",
    unit: "EA",
    rate: "459.17",
  },
  {
    sapNumber: "1460",
    shortDescription: "Install 9.2m Curved pole, lmr & Lamp",
    unit: "EA",
    rate: "454.2",
  },
  {
    sapNumber: "1470",
    shortDescription: "Installation of 17m stl pole, lmr & Lamp",
    unit: "EA",
    rate: "798.82",
  },
  {
    sapNumber: "1480",
    shortDescription: "Install 11.5m stl pole, lmr & Lamp",
    unit: "EA",
    rate: "563.82",
  },
  {
    sapNumber: "1490",
    shortDescription: "Install 7.2/9.2m stl pole, lmr & Lamp",
    unit: "EA",
    rate: "427.69",
  },
  {
    sapNumber: "1500",
    shortDescription: "Install 8/10.5m grp pole, lmr & Lamp",
    unit: "EA",
    rate: "388.78",
  },
  {
    sapNumber: "1510",
    shortDescription: "Plant concrete 7 to 7.5 metre pole",
    unit: "EA",
    rate: "364.07",
  },
  {
    sapNumber: "1520",
    shortDescription: "Plant concrete 9 to 9,3 metre pole",
    unit: "EA",
    rate: "372.48",
  },
  {
    sapNumber: "1530",
    shortDescription: "Plant concrete 10 to 11 metre pole",
    unit: "EA",
    rate: "425.19",
  },
  {
    sapNumber: "1540",
    shortDescription: "Plant concrete 11 & 7 m pole structor",
    unit: "EA",
    rate: "559.7",
  },
  {
    sapNumber: "1550",
    shortDescription: "plant 8/10.5 metre grp pole.",
    unit: "EA",
    rate: "365.81",
  },
  {
    sapNumber: "1560",
    shortDescription: "Install 7.2/9 m steel pole including insulation",
    unit: "EA",
    rate: "401.04",
  },
  {
    sapNumber: "1570",
    shortDescription: "Install 11.5m steel pole including insulation",
    unit: "EA",
    rate: "409.74",
  },
  {
    sapNumber: "1580",
    shortDescription: "Poles with more than one lintel",
    unit: "EA",
    rate: "385.62",
  },
  {
    sapNumber: "1590",
    shortDescription: "Poles with one lintel",
    unit: "EA",
    rate: "257.04",
  },
  {
    sapNumber: "1600",
    shortDescription: "Single strain fittings (120/95/50/25)",
    unit: "EA",
    rate: "132.07",
  },
  {
    sapNumber: "1610",
    shortDescription: "Double strain fitting for (120/95/50/25)",
    unit: "EA",
    rate: "139.6",
  },
  {
    sapNumber: "1620",
    shortDescription: "Single suspension fitting_(120/95/50)",
    unit: "EA",
    rate: "121.88",
  },
  {
    sapNumber: "1630",
    shortDescription: "T-off strain fitting for (120/95/50/25)",
    unit: "EA",
    rate: "127.16",
  },
  {
    sapNumber: "1640",
    shortDescription: "Install ABC single strain fitting (120-50)",
    unit: "EA",
    rate: "121.31",
  },
  {
    sapNumber: "1650",
    shortDescription: "Install ABC single suspension fitting (120-50)",
    unit: "EA",
    rate: "120",
  },
  {
    sapNumber: "1660",
    shortDescription: "Install ABC double strain fitting (120-50)",
    unit: "EA",
    rate: "127.98",
  },
  {
    sapNumber: "1670",
    shortDescription: "Install ABC t-off strain fitting (120-50)",
    unit: "EA",
    rate: "123.2",
  },
  {
    sapNumber: "1680",
    shortDescription: "Install IP clamp for tap-off one bolt",
    unit: "EA",
    rate: "96.96",
  },
  {
    sapNumber: "1690",
    shortDescription: "Install IP clamp for tap-off two bolt",
    unit: "EA",
    rate: "82.06",
  },
  {
    sapNumber: "1700",
    shortDescription: "Joint ABC 120 mm2 x 3 + n + e + s/l",
    unit: "EA",
    rate: "272.07",
  },
  {
    sapNumber: "1710",
    shortDescription: "Joint ABC 95 mm2 x 3 + n/e + s/l",
    unit: "EA",
    rate: "236.35",
  },
  {
    sapNumber: "1720",
    shortDescription: "Joint ABC 70 mm2 x 3 + n/e + s/l",
    unit: "EA",
    rate: "214.86",
  },
  {
    sapNumber: "1730",
    shortDescription: "Joint ABC 50 mm2 x 3 + n/e + s/l",
    unit: "EA",
    rate: "198.43",
  },
  {
    sapNumber: "1740",
    shortDescription: "Joint ABC 25 mm2 x 3 (s/l)",
    unit: "EA",
    rate: "169.52",
  },
  {
    sapNumber: "1750",
    shortDescription: "Joint ABC 10 mm2 split concentric LV cable",
    unit: "EA",
    rate: "119.83",
  },
  {
    sapNumber: "1760",
    shortDescription: "Terminate ABC 120 mm2 x 3 + n + e + s/l",
    unit: "EA",
    rate: "338.45",
  },
  {
    sapNumber: "1770",
    shortDescription: "Terminate ABC 95 mm2 x 3 + n/e + s/l",
    unit: "EA",
    rate: "273.04",
  },
  {
    sapNumber: "1780",
    shortDescription: "Terminate ABC 70 mm2 x 3 + n/e + s/l",
    unit: "EA",
    rate: "297.48",
  },
  {
    sapNumber: "1790",
    shortDescription: "Terminate ABC 50 mm2 x 3 + n/e + s/l",
    unit: "EA",
    rate: "255.63",
  },
  {
    sapNumber: "1800",
    shortDescription: "Terminate ABC 25 mm2 x 3 (s/l)",
    unit: "EA",
    rate: "185.81",
  },
  {
    sapNumber: "1810",
    shortDescription: "Inspection of LV overhead lines (per circuit)",
    unit: "EA",
    rate: "49.82",
  },
  {
    sapNumber: "1820",
    shortDescription: "Inspection of MV overhead lines (per circuit)",
    unit: "EA",
    rate: "53.67",
  },
  {
    sapNumber: "1830",
    shortDescription: "Retentioning of LV conductor ( per span)",
    unit: "EA",
    rate: "221.8",
  },
  {
    sapNumber: "1840",
    shortDescription: "Retentioning of MV conductor ( per span)",
    unit: "EA",
    rate: "274.35",
  },
  {
    sapNumber: "1850",
    shortDescription: "Splicing & retention snapped conductor",
    unit: "EA",
    rate: "336.07",
  },
  {
    sapNumber: "1860",
    shortDescription: "Bandit strap all cables per pole",
    unit: "EA",
    rate: "110.55",
  },
  {
    sapNumber: "1870",
    shortDescription: "Dressing a double shackle pole including assembly",
    unit: "EA",
    rate: "262.3",
  },
  {
    sapNumber: "1880",
    shortDescription: "Install of any outreach bracket",
    unit: "EA",
    rate: "128.33",
  },
  {
    sapNumber: "1890",
    shortDescription: "Installation of LV stay assembly",
    unit: "EA",
    rate: "225.74",
  },
  {
    sapNumber: "1900",
    shortDescription: "Installation of MV stay assembly",
    unit: "EA",
    rate: "225.03",
  },
  {
    sapNumber: "1910",
    shortDescription: "Installation of flying stay assembly",
    unit: "EA",
    rate: "245.18",
  },
  {
    sapNumber: "1920",
    shortDescription: "Install fly-stay-Pole including accessories",
    unit: "EA",
    rate: "224.85",
  },
  {
    sapNumber: "1930",
    shortDescription: "Install & fix inter-pole including all accessories",
    unit: "EA",
    rate: "244.94",
  },
  {
    sapNumber: "1940",
    shortDescription: "Install & fix Double Shackle pole including assembly",
    unit: "EA",
    rate: "295.13",
  },
  {
    sapNumber: "1950",
    shortDescription: "Install & fix Terminal-pole including accessories",
    unit: "EA",
    rate: "238.74",
  },
  {
    sapNumber: "1960",
    shortDescription: "Pole-mounted Distribution Box 1 & 3 phase boxes",
    unit: "EA",
    rate: "539.41",
  },
  {
    sapNumber: "1970",
    shortDescription: "Repair earth guards",
    unit: "EA",
    rate: "207.75",
  },
  {
    sapNumber: "1980",
    shortDescription: "Replace earth guards",
    unit: "EA",
    rate: "254.45",
  },
  {
    sapNumber: "1990",
    shortDescription: "Replace earth mats",
    unit: "EA",
    rate: "252.84",
  },
  {
    sapNumber: "2000",
    shortDescription: "Replace MV and LV insulators",
    unit: "EA",
    rate: "197.57",
  },
  {
    sapNumber: "2010",
    shortDescription: "Replace & install of X arm including insulation",
    unit: "EA",
    rate: "197.4",
  },
  {
    sapNumber: "2020",
    shortDescription: "Replace surge arrestors",
    unit: "EA",
    rate: "276.4",
  },
  {
    sapNumber: "2030",
    shortDescription: "Tree cutting under emergency",
    unit: "EA",
    rate: "399.22",
  },
  {
    sapNumber: "2040",
    shortDescription: "Install, Commissioning street light SDB/SPB on pole",
    unit: "EA",
    rate: "701.26",
  },
  {
    sapNumber: "2050",
    shortDescription: "Install pole-extension- 2,3m (Motor way)",
    unit: "EA",
    rate: "786.82",
  },
  {
    sapNumber: "2060",
    shortDescription: "Installation of lamps only (street lights)",
    unit: "EA",
    rate: "89.78",
  },
  {
    sapNumber: "2070",
    shortDescription: "Cleaning of Luminaire bowls",
    unit: "EA",
    rate: "65.87",
  },
  {
    sapNumber: "2080",
    shortDescription: "Install fitting & lamp (Different sizes)",
    unit: "EA",
    rate: "193.47",
  },
  {
    sapNumber: "2090",
    shortDescription: "Install stl lmr & 100mm-brack including Lamp",
    unit: "EA",
    rate: "253.36",
  },
  {
    sapNumber: "2100",
    shortDescription: "Remove and replace any size luminaire in",
    unit: "EA",
    rate: "191.67",
  },
  {
    sapNumber: "2110",
    shortDescription: "Install & wire Photo cell",
    unit: "EA",
    rate: "180.25",
  },
  {
    sapNumber: "2120",
    shortDescription: "Replace photo-electrical cell",
    unit: "EA",
    rate: "133.19",
  },
  {
    sapNumber: "2130",
    shortDescription: "Install Streetlight Control circuit in L",
    unit: "EA",
    rate: "496.08",
  },
  {
    sapNumber: "2140",
    shortDescription: "Remove and install a timer",
    unit: "EA",
    rate: "140.89",
  },
  {
    sapNumber: "2150",
    shortDescription: "Remove and install a ripple relay",
    unit: "EA",
    rate: "142.39",
  },
  {
    sapNumber: "2160",
    shortDescription: "Replace pole cover only",
    unit: "EA",
    rate: "95.63",
  },
  {
    sapNumber: "2170",
    shortDescription: "Straightening of skew poles",
    unit: "EA",
    rate: "179.1",
  },
  {
    sapNumber: "2180",
    shortDescription: "Install or replace street light bracket",
    unit: "EA",
    rate: "143.83",
  },
  {
    sapNumber: "2190",
    shortDescription: "Removal of welded covers",
    unit: "EA",
    rate: "148.69",
  },
  {
    sapNumber: "2200",
    shortDescription: "Welding of pole covers",
    unit: "EA",
    rate: "150.72",
  },
  {
    sapNumber: "2210",
    shortDescription: "Wire any pole size",
    unit: "EA",
    rate: "178.56",
  },
  {
    sapNumber: "2220",
    shortDescription: "Numbering of all poles",
    unit: "EA",
    rate: "91.87",
  },
  {
    sapNumber: "2230",
    shortDescription: "Numbering of Transmission towers",
    unit: "ea",
    rate: "144.46",
  },
  {
    sapNumber: "2240",
    shortDescription: "Painting of Transmission towers",
    unit: "ea",
    rate: "808.77",
  },
  {
    sapNumber: "2250",
    shortDescription: "Painting of all poles ( Any Length)",
    unit: "EA",
    rate: "204.41",
  },
  {
    sapNumber: "2260",
    shortDescription: "Sleeving and painting of poles",
    unit: "EA",
    rate: "195.97",
  },
  {
    sapNumber: "2270",
    shortDescription: "Install pole earths ,including all excavation works",
    unit: "EA",
    rate: "679.31",
  },
  {
    sapNumber: "2280",
    shortDescription: "Install stainless steel wire rope",
    unit: "EA",
    rate: "721.61",
  },
  {
    sapNumber: "2290",
    shortDescription: "Install +C315 trailing cable for High Masts",
    unit: "EA",
    rate: "561.31",
  },
  {
    sapNumber: "2300",
    shortDescription: "Install 4-way term block & photo cell",
    unit: "EA",
    rate: "151.12",
  },
  {
    sapNumber: "2310",
    shortDescription: "Install a by-pass switch for photo cell",
    unit: "EA",
    rate: "199.09",
  },
  {
    sapNumber: "2320",
    shortDescription: "Replace exist door with vandal proof",
    unit: "EA",
    rate: "704.18",
  },
  {
    sapNumber: "2330",
    shortDescription: "Disconnect and lower High Mast pole",
    unit: "EA",
    rate: "2141.06",
  },
  {
    sapNumber: "2340",
    shortDescription: "Replace-photo cell",
    unit: "EA",
    rate: "224.23",
  },
  {
    sapNumber: "2350",
    shortDescription:
      "Inspection and complete report of High Masts (checklist)",
    unit: "EA",
    rate: "745.87",
  },
  {
    sapNumber: "2360",
    shortDescription:
      "Install earth leakage isolator high mast Distribution Board",
    unit: "EA",
    rate: "438.85",
  },
  {
    sapNumber: "2370",
    shortDescription: "Lowering and raising of sectional poles (Scissor mast)",
    unit: "EA",
    rate: "1498.97",
  },
  {
    sapNumber: "2380",
    shortDescription: "Lowering and raising a luminaries (high mast)",
    unit: "EA",
    rate: "737.41",
  },
  {
    sapNumber: "2390",
    shortDescription: "Painting damaged galvanizing high mast",
    unit: "EA",
    rate: "208.36",
  },
  {
    sapNumber: "2400",
    shortDescription: "Lowering and raising a repaired high mast",
    unit: "EA",
    rate: "2114.54",
  },
  {
    sapNumber: "2410",
    shortDescription: "Replacing a faulty time switch",
    unit: "EA",
    rate: "206.38",
  },
  {
    sapNumber: "2420",
    shortDescription: "Supply and install holding down nuts per mast",
    unit: "EA",
    rate: "163.92",
  },
  {
    sapNumber: "2430",
    shortDescription: "Replace 1,5mm² x 3 core silicone insulation",
    unit: "EA",
    rate: "203.58",
  },
  {
    sapNumber: "2440",
    shortDescription: "Replace 16 amp 240 volt switched socket",
    unit: "EA",
    rate: "242.59",
  },
  {
    sapNumber: "2450",
    shortDescription: "Replace 2,5mm² x 5 core trailing cable",
    unit: "EA",
    rate: "396.78",
  },
  {
    sapNumber: "2460",
    shortDescription: "Replace 30 amp triple pole circuit",
    unit: "EA",
    rate: "226.1",
  },
  {
    sapNumber: "2470",
    shortDescription: "Replace 5 pin male plug top on trailing Cable",
    unit: "EA",
    rate: "339.19",
  },
  {
    sapNumber: "2480",
    shortDescription: "Replace 5 pin female socket outlet in mast",
    unit: "EA",
    rate: "294.5",
  },
  {
    sapNumber: "2490",
    shortDescription: "Supply & replace 5 pin male plug top on trailing Cable",
    unit: "EA",
    rate: "382",
  },
  {
    sapNumber: "2500",
    shortDescription: "Supply & replace 5 pin female socket outlet in mast",
    unit: "EA",
    rate: "317.55",
  },
  {
    sapNumber: "2510",
    shortDescription: "Replace 60 amp fuse base, cart and fuse",
    unit: "EA",
    rate: "167.91",
  },
  {
    sapNumber: "2520",
    shortDescription: "Replace cable separator",
    unit: "EA",
    rate: "373.75",
  },
  {
    sapNumber: "2530",
    shortDescription: "Replace complete Distribution Board inside mast",
    unit: "EA",
    rate: "861.21",
  },
  {
    sapNumber: "2540",
    shortDescription:
      "Supply & replace complete Distribution Board inside mast",
    unit: "EA",
    rate: "1426.47",
  },
  {
    sapNumber: "2550",
    shortDescription: "Replace compression glands for above",
    unit: "EA",
    rate: "121.65",
  },
  {
    sapNumber: "2560",
    shortDescription: "Replace faulty contactor",
    unit: "EA",
    rate: "191.73",
  },
  {
    sapNumber: "2570",
    shortDescription: "Replace fiberglass hood/canopy (luminaire)",
    unit: "EA",
    rate: "309.78",
  },
  {
    sapNumber: "2580",
    shortDescription: "Replace luminaires cable splitter box",
    unit: "EA",
    rate: "258.97",
  },
  {
    sapNumber: "2590",
    shortDescription: "Replace neutral bar on High mast Distribution Board",
    unit: "EA",
    rate: "158.43",
  },
  {
    sapNumber: "2600",
    shortDescription: "Replace 400 watt lamp",
    unit: "EA",
    rate: "175.26",
  },
  {
    sapNumber: "2610",
    shortDescription: "Replace pole cover",
    unit: "EA",
    rate: "176.49",
  },
  {
    sapNumber: "2620",
    shortDescription: "Replace pulley for trailing cable (High mast)",
    unit: "EA",
    rate: "507.75",
  },
  {
    sapNumber: "2630",
    shortDescription: "Replace pulley & housing 4 steel wire rope (High mast)",
    unit: "EA",
    rate: "524.6",
  },
  {
    sapNumber: "2640",
    shortDescription: "Replace steel wire ropes complete with accessories",
    unit: "EA",
    rate: "685.22",
  },
  {
    sapNumber: "2650",
    shortDescription: "Reset any size circuit breaker",
    unit: "EA",
    rate: "93.14",
  },
  {
    sapNumber: "2660",
    shortDescription: "Replace and reset single pole circuit",
    unit: "EA",
    rate: "205.68",
  },
  {
    sapNumber: "2670",
    shortDescription: "Replace and reset triple pole circuit",
    unit: "EA",
    rate: "218.33",
  },
  {
    sapNumber: "2680",
    shortDescription: "Supply and tack welding a new nuts",
    unit: "EA",
    rate: "165.32",
  },
  {
    sapNumber: "2690",
    shortDescription: "Tack welding a used nuts",
    unit: "EA",
    rate: "139.13",
  },
  {
    sapNumber: "2700",
    shortDescription: "Replace street light bracket complete - all sizes",
    unit: "EA",
    rate: "145.84",
  },
  {
    sapNumber: "2710",
    shortDescription: "Install street lighting luminaries-all sizes",
    unit: "EA",
    rate: "178.29",
  },
  {
    sapNumber: "2720",
    shortDescription: "Replace street lighting luminaires - all sizes",
    unit: "ea",
    rate: "299.86",
  },
  {
    sapNumber: "2730",
    shortDescription: "Supply and install complete Distribution Board",
    unit: "EA",
    rate: "1685.46",
  },
  {
    sapNumber: "2740",
    shortDescription: "Supply and mount stubby",
    unit: "EA",
    rate: "1363.32",
  },
  {
    sapNumber: "2750",
    shortDescription: "Touch up paint (per container)",
    unit: "EA",
    rate: "224.74",
  },
  {
    sapNumber: "2760",
    shortDescription: "Collection of material from stores",
    unit: "EA",
    rate: "933.23",
  },
  {
    sapNumber: "2770",
    shortDescription: "Compaction certificate (public roads )",
    unit: "EA",
    rate: "763.98",
  },
  {
    sapNumber: "2780",
    shortDescription: "Provision of security per 12hr shift",
    unit: "EA",
    rate: "1607.56",
  },
  {
    sapNumber: "2790",
    shortDescription: "Decommissioning of meters",
    unit: "EA",
    rate: "529.01",
  },
  {
    sapNumber: "2800",
    shortDescription: "Decommissioning of supply",
    unit: "EA",
    rate: "340.62",
  },
  {
    sapNumber: "2810",
    shortDescription: "Commissioning of supply",
    unit: "EA",
    rate: "424.94",
  },
  {
    sapNumber: "2820",
    shortDescription: "Transport cable and large equipment",
    unit: "EA",
    rate: "1411.49",
  },
  {
    sapNumber: "2830",
    shortDescription: "Prep of As-built drawings electronically",
    unit: "EA",
    rate: "1342.9",
  },
  {
    sapNumber: "2840",
    shortDescription: "Preparation of hand over documents",
    unit: "EA",
    rate: "1494.55",
  },
  {
    sapNumber: "2850",
    shortDescription: "Inspect/remove and replace 5 amp 1 phase meter",
    unit: "EA",
    rate: "208.34",
  },
  {
    sapNumber: "2860",
    shortDescription: "Inspect/remove & replace poly phase meter",
    unit: "EA",
    rate: "384.94",
  },
  {
    sapNumber: "2870",
    shortDescription: "Second visit to check for tampering",
    unit: "EA",
    rate: "328.89",
  },
  {
    sapNumber: "2880",
    shortDescription: "Hand prescribed notice for irregularity",
    unit: "EA",
    rate: "179.92",
  },
  {
    sapNumber: "2890",
    shortDescription: "Issue Engineer's certificate of completion",
    unit: "EA",
    rate: "1278.98",
  },
  {
    sapNumber: "2900",
    shortDescription: "Contractor to attend court/hearings (witness)",
    unit: "EA",
    rate: "1096.43",
  },
  {
    sapNumber: "2910",
    shortDescription: "Install hasp & staple",
    unit: "EA",
    rate: "308.64",
  },
  {
    sapNumber: "2920",
    shortDescription: "Make off and connect 2.5mm2 x 19 core pilot",
    unit: "EA",
    rate: "288",
  },
  {
    sapNumber: "2930",
    shortDescription: "Install including saddles 2.5mm² x19 core",
    unit: "EA",
    rate: "102.75",
  },
  {
    sapNumber: "2940",
    shortDescription: "Reprogram electronic meter",
    unit: "EA",
    rate: "205.39",
  },
  {
    sapNumber: "2950",
    shortDescription: "Replace old meter with new electronic meter",
    unit: "EA",
    rate: "486.13",
  },
  {
    sapNumber: "2960",
    shortDescription: "Provide download from electronic meter",
    unit: "EA",
    rate: "184.52",
  },
  {
    sapNumber: "2970",
    shortDescription: "Audit prepaid meters",
    unit: "EA",
    rate: "139.05",
  },
  {
    sapNumber: "2980",
    shortDescription: "Remove tamper/bridge meter",
    unit: "EA",
    rate: "199.26",
  },
  {
    sapNumber: "2990",
    shortDescription: "Install prepaid meter",
    unit: "EA",
    rate: "517.97",
  },
  {
    sapNumber: "3000",
    shortDescription: "Revisit/no access/can't locate",
    unit: "EA",
    rate: "197.67",
  },
  {
    sapNumber: "3010",
    shortDescription:
      "Install precast plinths for Pillar box including prepare ground works",
    unit: "EA",
    rate: "1052.33",
  },
  {
    sapNumber: "3020",
    shortDescription: "Install Pillar Box (Complete)",
    unit: "EA",
    rate: "959.63",
  },
  {
    sapNumber: "3030",
    shortDescription: "Pillar Box Repair",
    unit: "EA",
    rate: "678.75",
  },
  {
    sapNumber: "3040",
    shortDescription: "Painting of substations/Load Centre (brick sub)",
    unit: "m2",
    rate: "322.44",
  },
  {
    sapNumber: "3050",
    shortDescription: "Painting of load centre (Minisub)",
    unit: "EA",
    rate: "580.36",
  },
  {
    sapNumber: "3060",
    shortDescription: "Painting of pillar box",
    unit: "EA",
    rate: "442.58",
  },
  {
    sapNumber: "3070",
    shortDescription: "Labelling of Load Centre including pillar boxes",
    unit: "EA",
    rate: "419.1",
  },
  {
    sapNumber: "3080",
    shortDescription: "Security bars over louvers and windows",
    unit: "m2",
    rate: "1222.59",
  },
  {
    sapNumber: "3090",
    shortDescription: "Repair & Paint Substation Roof & Ceiling",
    unit: "m2",
    rate: "388.35",
  },
  {
    sapNumber: "3100",
    shortDescription: "Install of 2 m high palisade Fencing",
    unit: "M",
    rate: "1279.69",
  },
  {
    sapNumber: "3110",
    shortDescription: "Building work",
    unit: "m2",
    rate: "360.44",
  },
  {
    sapNumber: "3120",
    shortDescription: "Concrete work",
    unit: "m2",
    rate: "491.19",
  },
  {
    sapNumber: "3130",
    shortDescription: "Repair of Perimeter Fencing and walling",
    unit: "M",
    rate: "969.46",
  },
  {
    sapNumber: "3140",
    shortDescription: "Painting Perimeter Fencing and walling",
    unit: "M",
    rate: "172.44",
  },
  {
    sapNumber: "3150",
    shortDescription: "Repair Mss/Tss/Load centre door & hinges",
    unit: "EA",
    rate: "440.21",
  },
  {
    sapNumber: "3160",
    shortDescription: "Replace Mss/Tss/Load centre door & hinge",
    unit: "EA",
    rate: "867.51",
  },
  {
    sapNumber: "3170",
    shortDescription: "Repair substation doors & hinges",
    unit: "EA",
    rate: "505.72",
  },
  {
    sapNumber: "3180",
    shortDescription: "Replace substation doors & hinges",
    unit: "EA",
    rate: "821.45",
  },
  {
    sapNumber: "3190",
    shortDescription: "Replace hinges (all types)",
    unit: "EA",
    rate: "402.69",
  },
  {
    sapNumber: "3200",
    shortDescription: "Install 8mm checker plate (Cover) trench in subtn",
    unit: "m2",
    rate: "438.5",
  },
  {
    sapNumber: "3210",
    shortDescription: "Supply and Install Anti Theft Mss brackets",
    unit: "EA",
    rate: "693.73",
  },
  {
    sapNumber: "3220",
    shortDescription: "Removal of illegal connection",
    unit: "EA",
    rate: "524.62",
  },
  {
    sapNumber: "3230",
    shortDescription: "Clean substation & chamber (inside)",
    unit: "m2",
    rate: "1267.37",
  },
  {
    sapNumber: "3240",
    shortDescription: "Reinstate pole mounted pillar box doors",
    unit: "EA",
    rate: "973.28",
  },
  {
    sapNumber: "3250",
    shortDescription: "LPU site inspection and certificate installation",
    unit: "EA",
    rate: "670.7",
  },
  {
    sapNumber: "3260",
    shortDescription: "Install demand meter & commission",
    unit: "EA",
    rate: "783.34",
  },
  {
    sapNumber: "3270",
    shortDescription: "Install CT's and VT's",
    unit: "EA",
    rate: "678.94",
  },
  {
    sapNumber: "3280",
    shortDescription: "Install and commission a modem",
    unit: "EA",
    rate: "494.81",
  },
  {
    sapNumber: "3290",
    shortDescription: "install an external antennae",
    unit: "EA",
    rate: "580.71",
  },
  {
    sapNumber: "3300",
    shortDescription: "Standby - Special Events(per occasion)",
    unit: "EA",
    rate: "2422.41",
  },
  {
    sapNumber: "3310",
    shortDescription: "Supply of 4 core x 2.5mm CU PVC SWA PVC 600",
    unit: "M",
    rate: "46.69",
  },
  {
    sapNumber: "3320",
    shortDescription: "Supply of 4 core x 4mm CU PVC SWA PVC 600",
    unit: "M",
    rate: "71.62",
  },
  {
    sapNumber: "3330",
    shortDescription: "Supply of 12 core x 2.5mm CU PVC SWA PVC 600",
    unit: "M",
    rate: "63.92",
  },
  {
    sapNumber: "3340",
    shortDescription: "Supply of 12 core x 4mm CU PVC SWA PVC 600",
    unit: "M",
    rate: "110.52",
  },
  {
    sapNumber: "3350",
    shortDescription: "Laying of 4 core x 2.5mm CU PVC SWA PVC 600",
    unit: "M",
    rate: "30.69",
  },
  {
    sapNumber: "3360",
    shortDescription: "Laying of 4 core x 4mm CU PVC SWA PVC 600",
    unit: "M",
    rate: "24.99",
  },
  {
    sapNumber: "3370",
    shortDescription: "Laying of 12 core x 2.5mm CU PVC SWA PVC 600",
    unit: "M",
    rate: "29.48",
  },
  {
    sapNumber: "3380",
    shortDescription: "Laying of 12 core x 4mm CU PVC SWA PVC 600",
    unit: "M",
    rate: "38.48",
  },
  {
    sapNumber: "3390",
    shortDescription: "Install Pre paid meter Single Phase",
    unit: "EA",
    rate: "448.51",
  },
  {
    sapNumber: "3400",
    shortDescription: "Install Pre paid meter Three Phase",
    unit: "EA",
    rate: "659.15",
  },
  {
    sapNumber: "3410",
    shortDescription: "AMR Meter Installation",
    unit: "EA",
    rate: "706.45",
  },
  {
    sapNumber: "3420",
    shortDescription: "Install AMR Meter Modem",
    unit: "EA",
    rate: "311.62",
  },
  {
    sapNumber: "3430",
    shortDescription: "Install Protection Structure",
    unit: "EA",
    rate: "539.52",
  },
  {
    sapNumber: "3440",
    shortDescription: "Install Locks",
    unit: "EA",
    rate: "52.34",
  },
  {
    sapNumber: "3450",
    shortDescription: "Install a 40mm sleeve",
    unit: "M",
    rate: "43.62",
  },
  {
    sapNumber: "3460",
    shortDescription: "Install a 24SM HDD in fibre core sleeve",
    unit: "M",
    rate: "28.94",
  },
  {
    sapNumber: "3470",
    shortDescription: "Installation of 48SM HDD fibre core in a sleeve",
    unit: "M",
    rate: "42.89",
  },
  {
    sapNumber: "3480",
    shortDescription: "Fusion splicing per fibre core",
    unit: "EA",
    rate: "154.14",
  },
  {
    sapNumber: "3490",
    shortDescription: "Term. of 24 fibre in p/panel including splicing",
    unit: "EA",
    rate: "2843.84",
  },
  {
    sapNumber: "3500",
    shortDescription: "Term. of 48 fibre in p/panel including splicing",
    unit: "EA",
    rate: "5279.88",
  },
  {
    sapNumber: "3510",
    shortDescription: "Optical testing with light source and po",
    unit: "EA",
    rate: "235.91",
  },
  {
    sapNumber: "3520",
    shortDescription: "OTDR testing including traces in hard an",
    unit: "EA",
    rate: "1168.18",
  },
  {
    sapNumber: "3530",
    shortDescription: "Installation of demand meters",
    unit: "EA",
    rate: "810.39",
  },
  {
    sapNumber: "3540",
    shortDescription: "Installation of modems",
    unit: "EA",
    rate: "385",
  },
  {
    sapNumber: "3550",
    shortDescription: "Installation of sim cards",
    unit: "EA",
    rate: "362.22",
  },
  {
    sapNumber: "3560",
    shortDescription: "Second visit to customer to install prepaid meter",
    unit: "EA",
    rate: "446.31",
  },
  {
    sapNumber: "3570",
    shortDescription: "Stringing of AIRDAC 10mm & 16mm",
    unit: "M",
    rate: "45.14",
  },
  {
    sapNumber: "3580",
    shortDescription: "String ABC (new) of 16 to 25mm 2/3 core (per span)",
    unit: "EA",
    rate: "80.55",
  },
  {
    sapNumber: "3590",
    shortDescription: "String ABC (new) of 35mm2 (4/5 core) (per span)",
    unit: "EA",
    rate: "102.5",
  },
  {
    sapNumber: "3600",
    shortDescription: "String ABC (new) of 50mm² (4/5 core) (per span)",
    unit: "EA",
    rate: "166.71",
  },
  {
    sapNumber: "3610",
    shortDescription: "String ABC (new) of 95mm² (4/5 core) (per span)",
    unit: "EA",
    rate: "174.29",
  },
  {
    sapNumber: "3620",
    shortDescription: "String abc (new) of 120mm² (4/5 core+SL) (per span)",
    unit: "EA",
    rate: "190.19",
  },
  {
    sapNumber: "3630",
    shortDescription: "Retentioning of ABC of 35mm²(4 core) (per span)",
    unit: "EA",
    rate: "23.14",
  },
  {
    sapNumber: "3640",
    shortDescription: "Retentioning of ABC of 50mm² (4 core) (per span)",
    unit: "EA",
    rate: "26.78",
  },
  {
    sapNumber: "3650",
    shortDescription: "Retentioning of ABC of 35mm²(4 core plu (per span)",
    unit: "EA",
    rate: "32.69",
  },
  {
    sapNumber: "3660",
    shortDescription: "Retentioning of ABC of 50mm²(4 core plu (per span)",
    unit: "EA",
    rate: "41.47",
  },
  {
    sapNumber: "3670",
    shortDescription: "Retentioning of ABC of 95mm²(4 core plu (per span)",
    unit: "EA",
    rate: "66.6",
  },
  {
    sapNumber: "3680",
    shortDescription: "Retentioning of ABC of 120mm²(4 core pl (per span)",
    unit: "EA",
    rate: "78.17",
  },
  {
    sapNumber: "3690",
    shortDescription: "Removal of ABC 35mm² (per span)",
    unit: "EA",
    rate: "25",
  },
  {
    sapNumber: "3700",
    shortDescription: "Removal of ABC 50mm² (per span)",
    unit: "EA",
    rate: "28.33",
  },
  {
    sapNumber: "3710",
    shortDescription: "Removal of ABC 95mm² (per span)",
    unit: "EA",
    rate: "38.95",
  },
  {
    sapNumber: "3720",
    shortDescription: "Removal of ABC 120mm² (per span)",
    unit: "EA",
    rate: "46.47",
  },
  {
    sapNumber: "3730",
    shortDescription: "Retentioning of Fox per conductor",
    unit: "EA",
    rate: "16.38",
  },
  {
    sapNumber: "3740",
    shortDescription: "Retentioning of Mink per conductor",
    unit: "EA",
    rate: "17.93",
  },
  {
    sapNumber: "3750",
    shortDescription: "Retentioning of Hare per conductor",
    unit: "EA",
    rate: "18.97",
  },
  {
    sapNumber: "3760",
    shortDescription: "Retentioning of Squirrels per conductor",
    unit: "EA",
    rate: "20.79",
  },
  {
    sapNumber: "3770",
    shortDescription: "Retentioning of Ferret per conductor",
    unit: "EA",
    rate: "30.08",
  },
  {
    sapNumber: "3780",
    shortDescription: "Stringing of Fox per conductor",
    unit: "EA",
    rate: "36.18",
  },
  {
    sapNumber: "3790",
    shortDescription: "Stringing of Mink per conductor",
    unit: "EA",
    rate: "50.61",
  },
  {
    sapNumber: "3800",
    shortDescription: "Stringing of Hare per conductor",
    unit: "EA",
    rate: "55.92",
  },
  {
    sapNumber: "3810",
    shortDescription: "Removal of Fox per line (Not ABC)",
    unit: "EA",
    rate: "69.08",
  },
  {
    sapNumber: "3820",
    shortDescription: "Removal of Mink per line (Not ABC)",
    unit: "EA",
    rate: "27.01",
  },
  {
    sapNumber: "3830",
    shortDescription: "Removal of Hare per line (Not ABC)",
    unit: "EA",
    rate: "45.32",
  },
  {
    sapNumber: "3840",
    shortDescription: "transportation of high mast",
    unit: "EA",
    rate: "9141.3",
  },
  {
    sapNumber: "3850",
    shortDescription: "Install a single phase Split Prepaid Meter",
    unit: "EA",
    rate: "698.16",
  },
  {
    sapNumber: "3860",
    shortDescription: "Install a 3 phase Split Prepaid Meter",
    unit: "EA",
    rate: "809.05",
  },
  {
    sapNumber: "3870",
    shortDescription: "programming Customer CIU to meter",
    unit: "EA",
    rate: "430.28",
  },
  {
    sapNumber: "3880",
    shortDescription: "Replace CMK with Anti-Vandal CMK – C",
    unit: "EA",
    rate: "1605.44",
  },
  {
    sapNumber: "3890",
    shortDescription: "Replace SDB with Anti-Vandal CDU (pole mntd)(D)",
    unit: "EA",
    rate: "1484.7",
  },
  {
    sapNumber: "3900",
    shortDescription: "Install, test and comm. RAT#s in MSS (E)",
    unit: "EA",
    rate: "613.61",
  },
  {
    sapNumber: "3910",
    shortDescription: "Replace CMK with Protection Enclo & In (F)",
    unit: "EA",
    rate: "2088.31",
  },
  {
    sapNumber: "3920",
    shortDescription: "Replace SDB with anti-Vandal, pole mntd including dec",
    unit: "EA",
    rate: "1504.77",
  },
  {
    sapNumber: "3930",
    shortDescription: "Connecting of kW/h meters",
    unit: "EA",
    rate: "276.25",
  },
  {
    sapNumber: "3940",
    shortDescription: "Joint 10 mm2 split concentric LV cab",
    unit: "EA",
    rate: "104.45",
  },
  {
    sapNumber: "3950",
    shortDescription: "Install double strain fitting",
    unit: "EA",
    rate: "97.48",
  },
  {
    sapNumber: "3960",
    shortDescription: "Install suspension fitting",
    unit: "EA",
    rate: "60.6",
  },
  {
    sapNumber: "3970",
    shortDescription: "Install IPCS",
    unit: "EA",
    rate: "36.83",
  },
  {
    sapNumber: "3980",
    shortDescription: "Bandit strapping (per pole)",
    unit: "EA",
    rate: "48.47",
  },
  {
    sapNumber: "3990",
    shortDescription: "Label service cables",
    unit: "EA",
    rate: "34.51",
  },
  {
    sapNumber: "4000",
    shortDescription: "Decommission existing LV line",
    unit: "EA",
    rate: "383.95",
  },
  {
    sapNumber: "4010",
    shortDescription: "Removal of redundant cables off pole",
    unit: "M",
    rate: "104.95",
  },
  {
    sapNumber: "4020",
    shortDescription: "Installation of stay pedestal",
    unit: "EA",
    rate: "280.41",
  },
  {
    sapNumber: "4030",
    shortDescription: "Installation of plain Mast DIS 1",
    unit: "EA",
    rate: "470.52",
  },
  {
    sapNumber: "4040",
    shortDescription: "Under road drilling",
    unit: "M",
    rate: "1109.59",
  },
  {
    sapNumber: "4050",
    shortDescription:
      "Hydraulic crane truck 160-300 ton with boom reaching 50 metres.",
    unit: "HR",
    rate: "116379.9",
  },

  // Catalog items with categories
  {
    sapNumber: "391",
    shortDescription: "TAPE PVC TYPE B YELLOW",
    rate: "39.16",
    unit: "EA",
    category: "Insulating Tape",
  },
  {
    sapNumber: "392",
    shortDescription: "TAPE PVC TYPE B BLUE",
    rate: "40.04",
    unit: "EA",
    category: "Insulating Tape",
  },
  {
    sapNumber: "393",
    shortDescription: "LUG 35-95 MECH M12",
    rate: "177.85",
    unit: "EA",
    category: "Cable Lugs",
  },
  {
    sapNumber: "424",
    shortDescription: "MSS TB 315KVA DR DYN11 3MM THICK AV SF6",
    rate: "615037.43",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "425",
    shortDescription: "MSS TB 500KVA DR DYN11 3MM THICK AV SF6",
    rate: "686021.62",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "426",
    shortDescription: "MSS TB 630KVA DR DYN11 3MM THICK AV SF6",
    rate: "710370.03",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "427",
    shortDescription: "MSS TB 1000KVA DR DYN11 3MM THICK AV SF6",
    rate: "780430.33",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "430",
    shortDescription: "Lamp:250W,230V,TUB,E40,MH",
    rate: "365.48",
    unit: "EA",
    category: "Metal Halide Lamps",
  },
  {
    sapNumber: "453",
    shortDescription: "CAB LV ABC 25 2C AL",
    rate: "180.09",
    unit: "M",
    category: "Aerial Bundled Conductor",
  },
  {
    sapNumber: "454",
    shortDescription: "CAB LV ABC 50 5C AL",
    rate: "288.09",
    unit: "M",
    category: "Aerial Bundled Conductor",
  },
  {
    sapNumber: "455",
    shortDescription: "CAB LV ABC 95 5C AL",
    rate: "392.39",
    unit: "M",
    category: "Aerial Bundled Conductor",
  },
  {
    sapNumber: "456",
    shortDescription: "CAB LV ABC 120 5C AL",
    rate: "463.16",
    unit: "M",
    category: "Aerial Bundled Conductor",
  },
  {
    sapNumber: "480",
    shortDescription: "Pole:13.8m,12m,With Access Cover,Steel",
    rate: "10264.92",
    unit: "EA",
    category: "Poles & Masts",
  },
  {
    sapNumber: "481",
    shortDescription: "Pole:11.5m,10m,With Access Cover,SteelA6",
    rate: "7616.9",
    unit: "EA",
    category: "Poles & Masts",
  },
  {
    sapNumber: "482",
    shortDescription: "Pole:9.2m,8m,With Access Cover,Steel A7",
    rate: "6253.92",
    unit: "EA",
    category: "Poles & Masts",
  },
  {
    sapNumber: "490",
    shortDescription: "Bracket:Lighting,Mounting Luminaires",
    rate: "997.07",
    unit: "EA",
    category: "Streetlight Accessories",
  },
  {
    sapNumber: "513",
    shortDescription: "PADLOCK LV (C) YELLOW",
    rate: "678.33",
    unit: "EA",
    category: "General Goods",
  },
  {
    sapNumber: "517",
    shortDescription: "IPC 25-95/25-95 ABC MAIN",
    rate: "102.75",
    unit: "EA",
    category: "Overhead Network Accessories",
  },
  {
    sapNumber: "518",
    shortDescription: "IPC 25-95/10-16 ABC SERVICE",
    rate: "89.26",
    unit: "EA",
    category: "Overhead Network Accessories",
  },
  {
    sapNumber: "519",
    shortDescription: "IPC 25-95/1.5-6 ABC SL",
    rate: "88.57",
    unit: "EA",
    category: "Overhead Network Accessories",
  },
  {
    sapNumber: "520",
    shortDescription: "IPC 120/120 ABC MAIN",
    rate: "122.93",
    unit: "EA",
    category: "Overhead Network Accessories",
  },
  {
    sapNumber: "521",
    shortDescription: "IPC 120/10-16 ABC SERVICE",
    rate: "117.56",
    unit: "EA",
    category: "Overhead Network Accessories",
  },
  {
    sapNumber: "541",
    shortDescription: "STRAIN FITTING LV ABC",
    rate: "148.85",
    unit: "EA",
    category: "Overhead Network Accessories",
  },
  {
    sapNumber: "544",
    shortDescription: "Suspension Fitting:PS 54-50-35,Black",
    rate: "170.87",
    unit: "EA",
    category: "Overhead Network Accessories",
  },
  {
    sapNumber: "551",
    shortDescription: "Insulating Oil:Regen,Non-Exchange,210l",
    rate: "6124.02",
    unit: "EA",
    category: "Transformer Insulating Oil",
  },
  {
    sapNumber: "571",
    shortDescription: "METERING UNIT 11KV 3MM THICK RMU SF6",
    rate: "434078.55",
    unit: "EA",
    category: "Metering Units",
  },
  {
    sapNumber: "583",
    shortDescription: "JNT 11 TRANS PI-XLPE 95-185 3C",
    rate: "5079.02",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "589",
    shortDescription: "JNT 11 XLPE 95-185 3C",
    rate: "4580.26",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "635",
    shortDescription: "FUSE LV 10A 80KA STRL CRTR 38 MM",
    rate: "121.24",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "637",
    shortDescription: "FUSECARRIER FOR CART FUSE STREETLIGHT LV",
    rate: "193.29",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "762",
    shortDescription: "FUSE CARRIER NH-2 ABC POLE MOUNTED",
    rate: "3145.1",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "763",
    shortDescription: "STRAIN ASSEMBLY ABC",
    rate: "310.68",
    unit: "EA",
    category: "Network Accessories",
  },
  {
    sapNumber: "802",
    shortDescription: "TX: 315kVA, 11/6.6kV/415V, DYN11, Pole",
    rate: "281374.2",
    unit: "EA",
    category: "Distribution Transformers",
  },
  {
    sapNumber: "913",
    shortDescription: "TRM 11 185-300 3C TYPE 4 SSC INDOOR",
    rate: "7883.54",
    unit: "EA",
    category: "Cable Terminations",
  },
  {
    sapNumber: "915",
    shortDescription: "JNT 11 XLPE 185-300 3C",
    rate: "6467.7",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "1022",
    shortDescription: "FUSE LV 250A 80KA TYPE NH-1 DIST",
    rate: "208.48",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "1034",
    shortDescription: "Fuse Assembly:P/Mounted,Holders & Arm",
    rate: "1052.34",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "1162",
    shortDescription: "CAB 132 XLPE 1000 1C AL CSA",
    rate: "2057.11",
    unit: "M",
    category: "High Voltage Cable",
  },
  {
    sapNumber: "1412",
    shortDescription: "TX: 315kVA, 11kV/415V, DYN11",
    rate: "233171.03",
    unit: "EA",
    category: "Distribution Transformers",
  },
  {
    sapNumber: "1418",
    shortDescription: "TRF:500kV.A,11/0.415kV SGL Ratio,DYN11",
    rate: "322804.16",
    unit: "EA",
    category: "Distribution Transformers",
  },
  {
    sapNumber: "1441",
    shortDescription: "TRM 11 XLPE 95 - 185 3C INDOOR",
    rate: "7051.07",
    unit: "EA",
    category: "Cable Terminations",
  },
  {
    sapNumber: "1511",
    shortDescription: "CAB LV PVC FLEXBLE 95 1C CU YELLW RB3922",
    rate: "544.87",
    unit: "M",
    category: "House Wire",
  },
  {
    sapNumber: "1691",
    shortDescription: "RMU:11kV,SF6,3 X 360A SD (Outdoor)",
    rate: "274489.51",
    unit: "EA",
    category: "Ring Main Units",
  },
  {
    sapNumber: "1692",
    shortDescription: "RMU:11kV,SF6 4 X 360A SD (Indoor)",
    rate: "254304.63",
    unit: "EA",
    category: "Ring Main Units",
  },
  {
    sapNumber: "1693",
    shortDescription: "RMU:11kV,SF6 4 X 630A SD (Outdoor)",
    rate: "335490.34",
    unit: "EA",
    category: "Ring Main Units",
  },
  {
    sapNumber: "1694",
    shortDescription: "RMU:11kV,SF6 2 X 630A SD & CB (Indoor)",
    rate: "218733.55",
    unit: "EA",
    category: "Ring Main Units",
  },
  {
    sapNumber: "1697",
    shortDescription: "RMU:11kV,SF6 3 X 630A SD & CB (Outdoor)",
    rate: "370153.63",
    unit: "EA",
    category: "Ring Main Units",
  },
  {
    sapNumber: "1721",
    shortDescription: "CAB LV PVC 16 1C CU BLUE (RB3925)",
    rate: "341.09",
    unit: "M",
    category: "House Wire",
  },
  {
    sapNumber: "1722",
    shortDescription: "CAB LV PVC 2,5 1C CU RED",
    rate: "133.32",
    unit: "M",
    category: "House Wire",
  },
  {
    sapNumber: "1723",
    shortDescription: "CAB LV PVC 2,5 1C CU BLACK",
    rate: "361.49",
    unit: "M",
    category: "House Wire",
  },
  {
    sapNumber: "1724",
    shortDescription: "CAB LV PVC 2,5 1C CU BLUE",
    rate: "147.04",
    unit: "M",
    category: "House Wire",
  },
  {
    sapNumber: "1725",
    shortDescription: "CAB LV PVC 2,5 1C CU YELLOW & GREEN",
    rate: "144.37",
    unit: "M",
    category: "House Wire",
  },
  {
    sapNumber: "1726",
    shortDescription: "CAB LV PVC 16 1C CU RED (RB3923)",
    rate: "349.96",
    unit: "M",
    category: "House Wire",
  },
  {
    sapNumber: "1727",
    shortDescription: "CAB LV PVC 16 1C CU BLACK (RB3926)",
    rate: "352.68",
    unit: "M",
    category: "House Wire",
  },
  {
    sapNumber: "1853",
    shortDescription: "POLE COVER PLASTIC UNIVERSAL",
    rate: "372.62",
    unit: "EA",
    category: "Streetlight Accessories",
  },
  {
    sapNumber: "2194",
    shortDescription: "JNT 11 TRANS PI-XLPE 185-300 3C",
    rate: "5524.34",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "2310",
    shortDescription: "Stay Kit Complete:Low Voltage (LV)",
    rate: "1227.26",
    unit: "EA",
    category: "Network Accessories",
  },
  {
    sapNumber: "2312",
    shortDescription: "TX: 500kVA, 22kV/415V, DYN11, Pole",
    rate: "312407.43",
    unit: "EA",
    category: "Distribution Transformers",
  },
  {
    sapNumber: "2402",
    shortDescription: "FRL 16-35 MECH SC",
    rate: "140.92",
    unit: "EA",
    category: "Cable Ferrules",
  },
  {
    sapNumber: "2921",
    shortDescription: "CAB LV ABC 25 4C AL",
    rate: "245.9",
    unit: "M",
    category: "Aerial Bundled Conductor",
  },
  {
    sapNumber: "3232",
    shortDescription: "CAB 11 XLPE 185 3C AL SWA",
    rate: "1309.27",
    unit: "M",
    category: "Medium Voltage Cable",
  },
  {
    sapNumber: "3234",
    shortDescription: "CAB 11 XLPE 300 3C AL SWA",
    rate: "1722.82",
    unit: "M",
    category: "Medium Voltage Cable",
  },
  {
    sapNumber: "3531",
    shortDescription: "LED streetlight (250W HPS/T equivalent)",
    rate: "4571.51",
    unit: "EA",
    category: "Streetlight Luminaires",
  },
  {
    sapNumber: "3532",
    shortDescription: "LED streetlight (100W HPS/T equivalent)",
    rate: "3019.07",
    unit: "EA",
    category: "Streetlight Luminaires",
  },
  {
    sapNumber: "3533",
    shortDescription: "LED streetlight (70W HPS/T equivalent)",
    rate: "2965.94",
    unit: "EA",
    category: "Streetlight Luminaires",
  },
  {
    sapNumber: "3534",
    shortDescription: "LED streetlight (400W HPS/T equivalent)",
    rate: "5669.81",
    unit: "EA",
    category: "Streetlight Luminaires",
  },
  {
    sapNumber: "3582",
    shortDescription: "MSS TB 500KVA SR DYN11 3MM THICK AV SF6",
    rate: "680724.06",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3583",
    shortDescription: "MSS TB 315KVA DR DYN11 6MM THICK AV SF6",
    rate: "662262.41",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3584",
    shortDescription: "MSS TB 500KVA SR DYN11 6MM THICK AV SF6",
    rate: "736317.44",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3585",
    shortDescription: "MSS TB 500KVA DR DYN11 6MM THICK AV SF6",
    rate: "715531.01",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3586",
    shortDescription: "MSS TB 630KVA DR DYN11 6MM THICK AV SF6",
    rate: "794049.83",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3587",
    shortDescription: "MSS TB 1000KVA DR DYN11 6MM THICK AV SF6",
    rate: "815533.98",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3654",
    shortDescription: "HTLS 1227A 21.79MM DIAMETER",
    rate: "3233.91",
    unit: "M",
    category: "High Temperature Low Sag Conductor",
  },
  {
    sapNumber: "3701",
    shortDescription: "MSS 315KVA DR DYN11 3MM AV DRY TYPE TRFR",
    rate: "555382.92",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3702",
    shortDescription: "MSS TB 315KVA SR DYN11 3MM THICK AV SF6",
    rate: "699542.18",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3703",
    shortDescription: "MSS TB 500KVA DR DYN11 3MM THICK AV SF6D",
    rate: "715731.56",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3706",
    shortDescription: "MSS 315KVA DR DYN11 6MM AV DRY TYPE TRFR",
    rate: "600783.38",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3708",
    shortDescription: "MSS 500KVA SR DYN11 3MM SF6DRY TYPE TRFR",
    rate: "596786.59",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3709",
    shortDescription: "MSS 630KVA DR DYN11 3MM SF6DRY TYPE TRFR",
    rate: "679049.3",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3710",
    shortDescription: "MSS 1000KVA DR DYN11 3MMSF6DRY TYPE TRFR",
    rate: "640804.21",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3711",
    shortDescription: "MSS 500KVA SR DYN11 6MM SF6DRY TYPE TRFR",
    rate: "614818.37",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3713",
    shortDescription: "MSS 630KVA DR DYN11 6MM SF6DRY TYPE TRFR",
    rate: "695372.73",
    unit: "EA",
    category: "Miniature Substations",
  },
  {
    sapNumber: "3922",
    shortDescription: "CAB LV XLPE FLEXIBLE 120 1C AL YELLOW",
    rate: "365.02",
    unit: "M",
    category: "House Wire",
  },
  {
    sapNumber: "3928",
    shortDescription: "CAB LV XLPE 25 2C AL SWA",
    rate: "182.41",
    unit: "M",
    category: "Low Voltage Cable",
  },
  {
    sapNumber: "3929",
    shortDescription: "CAB LV XLPE 25 4C AL SWA",
    rate: "213.1",
    unit: "M",
    category: "Low Voltage Cable",
  },
  {
    sapNumber: "3930",
    shortDescription: "CAB LV XLPE 35 4C AL SWA",
    rate: "278.24",
    unit: "M",
    category: "Low Voltage Cable",
  },
  {
    sapNumber: "3931",
    shortDescription: "CAB LV XLPE 50 4C AL SWA",
    rate: "371.6",
    unit: "M",
    category: "Low Voltage Cable",
  },
  {
    sapNumber: "3932",
    shortDescription: "CAB LV XLPE 95 4C AL SWA",
    rate: "564.01",
    unit: "M",
    category: "Low Voltage Cable",
  },
  {
    sapNumber: "3933",
    shortDescription: "CAB LV XLPE 150 4C AL SWA",
    rate: "814.55",
    unit: "M",
    category: "Low Voltage Cable",
  },
  {
    sapNumber: "3934",
    shortDescription: "CAB LV XLPE 240 4C AL SWA",
    rate: "1269.93",
    unit: "M",
    category: "Low Voltage Cable",
  },
  {
    sapNumber: "4044",
    shortDescription: "L&G 1PHASE PREPAID 230V SPLIT UNIT",
    rate: "3950.8",
    unit: "EA",
    category: "Electricity Meters",
  },
  {
    sapNumber: "4284",
    shortDescription: "HEXING CUSTOMER INTERFACE UNIT(CIU)",
    rate: "889.51",
    unit: "EA",
    category: "Electricity Meters",
  },
  {
    sapNumber: "4285",
    shortDescription: "HEXING 3PHASE 4WIRE POSTPAID 400V",
    rate: "4239.82",
    unit: "EA",
    category: "Electricity Meters",
  },
  {
    sapNumber: "5044",
    shortDescription: "CAB LV 16 SCC CU",
    rate: "233.57",
    unit: "M",
    category: "Aerial Bundled Conductor",
  },
  {
    sapNumber: "5063",
    shortDescription: "CAB LV 10 SCC CU",
    rate: "145.5",
    unit: "M",
    category: "Aerial Bundled Conductor",
  },
  {
    sapNumber: "5082",
    shortDescription: "CAB LV XLPE 240 4C AL SWA",
    rate: "1517.79",
    unit: "M",
    category: "Low Voltage Cable",
  },
  {
    sapNumber: "5201",
    shortDescription: "MSS PLINTH TYPE B",
    rate: "11641.91",
    unit: "EA",
    category: "Plinths",
  },
  {
    sapNumber: "5218",
    shortDescription: "CONTACTOR SL 80A 3 PHASE AC3",
    rate: "1835.11",
    unit: "EA",
    category: "Streetlight Accessories",
  },
  {
    sapNumber: "5219",
    shortDescription: "CONTACTOR SL 40A 3 PHASE AC3",
    rate: "1080.51",
    unit: "EA",
    category: "Streetlight Accessories",
  },
  {
    sapNumber: "5253",
    shortDescription: "LUMINAIRE: STREET LIGHT 100 W HPS CO SE",
    rate: "1745.08",
    unit: "EA",
    category: "Streetlight Luminaires",
  },
  {
    sapNumber: "5291",
    shortDescription: "JNT LV 70-120 4C",
    rate: "2151.67",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "5294",
    shortDescription: "JNT LV 185-240 4C",
    rate: "3578.78",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "5306",
    shortDescription: "TX: 500kVA, 11/6.6kV/415V, DYN11",
    rate: "267556.18",
    unit: "EA",
    category: "Distribution Transformers",
  },
  {
    sapNumber: "5308",
    shortDescription: "TX: 315kVA,11/ 6.6kV/415V, DYN11",
    rate: "248138.38",
    unit: "EA",
    category: "Distribution Transformers",
  },
  {
    sapNumber: "5313",
    shortDescription: "MCCB 160 - 400A TP LV 35KA",
    rate: "11713.61",
    unit: "EA",
    category: "Miniature Circuit Breakers",
  },
  {
    sapNumber: "5315",
    shortDescription: "MCB 100A 6KA SP",
    rate: "744.21",
    unit: "EA",
    category: "Moulded Case Circuit Breakers",
  },
  {
    sapNumber: "5341",
    shortDescription: "JNT LV 120-185 4C",
    rate: "3420.7",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "5348",
    shortDescription: "FRL 35-95 MECH SC",
    rate: "205.93",
    unit: "EA",
    category: "Cable Ferrules",
  },
  {
    sapNumber: "5351",
    shortDescription: "FRL 95-240 MECH SC",
    rate: "311.25",
    unit: "EA",
    category: "Cable Ferrules",
  },
  {
    sapNumber: "5353",
    shortDescription: "LUG 95-240 MECH M12",
    rate: "260.39",
    unit: "EA",
    category: "Cable Lugs",
  },
  {
    sapNumber: "5396",
    shortDescription: "Spigot Adaptor:Reference A(1)",
    rate: "452.54",
    unit: "EA",
    category: "Streetlight Accessories",
  },
  {
    sapNumber: "5451",
    shortDescription: "MCB 80A 6KA SP",
    rate: "727.87",
    unit: "EA",
    category: "Moulded Case Circuit Breakers",
  },
  {
    sapNumber: "5453",
    shortDescription: "MCB:230V,20A,2.5kA,Single Pole",
    rate: "409.94",
    unit: "EA",
    category: "Moulded Case Circuit Breakers",
  },
  {
    sapNumber: "5455",
    shortDescription: "MCB 20A 6KA SP",
    rate: "273.06",
    unit: "EA",
    category: "Moulded Case Circuit Breakers",
  },
  {
    sapNumber: "5472",
    shortDescription: "Clamp U:Steel,12mm",
    rate: "165.3",
    unit: "EA",
    category: "Overhead Network Accessories",
  },
  {
    sapNumber: "5494",
    shortDescription: "MCB 40A 6KA SP",
    rate: "295.96",
    unit: "EA",
    category: "Moulded Case Circuit Breakers",
  },
  {
    sapNumber: "5510",
    shortDescription: "Connector Screw:Term, No. 2",
    rate: "51.46",
    unit: "EA",
    category: "Electrical Accessories",
  },
  {
    sapNumber: "5511",
    shortDescription: "End Connector,Insulating Sleeve:No 2,PVC",
    rate: "49.58",
    unit: "EA",
    category: "Electrical Accessories",
  },
  {
    sapNumber: "5512",
    shortDescription: "TAPE SELF-FUSING 9M X 25MM",
    rate: "199.35",
    unit: "EA",
    category: "Insulating Tape",
  },
  {
    sapNumber: "5541",
    shortDescription: "FUSE LV 315A 80KA SLOT TYPE J DIST 83MM",
    rate: "325.07",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "5543",
    shortDescription: "FUSE LV 400A 80KA SLOT TYPE J DIST 83MM",
    rate: "373.76",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "5613",
    shortDescription: "CableTies:T120R,388X7.8mm,L,1EA=1Pkt 50",
    rate: "311.85",
    unit: "EA",
    category: "Cable Ties",
  },
  {
    sapNumber: "5614",
    shortDescription: "JNT LV 4-10 4C",
    rate: "594.41",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "5615",
    shortDescription: "JNT LV 16-25 4C",
    rate: "1124.95",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "5616",
    shortDescription: "JNT LV 35-70 4C",
    rate: "1662.14",
    unit: "EA",
    category: "Cable Joints",
  },
  {
    sapNumber: "5665",
    shortDescription: "TRM 11 95-185 SEPARABLE CONNECTOR INDOOR",
    rate: "6107.68",
    unit: "EA",
    category: "Cable Terminations",
  },
  {
    sapNumber: "5685",
    shortDescription: "FUSE LV 6A 80KA OFFSET TAG 58 MM",
    rate: "163.26",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "5709",
    shortDescription: "Fuse Carrier,Type J LV Fuse 83mm FC",
    rate: "341.37",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "5726",
    shortDescription: "FUSE BASE AND CARRIER FOR DIST LV FUSE",
    rate: "286.58",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "5786",
    shortDescription: "LUMINAIRE:STREET LIGHT 70 W HPS CO SE",
    rate: "2353.63",
    unit: "EA",
    category: "Streetlight Luminaires",
  },
  {
    sapNumber: "5790",
    shortDescription: "Floodlight:400W,Narrow Beam,HPS",
    rate: "3401.28",
    unit: "EA",
    category: "Floodlight Luminaires",
  },
  {
    sapNumber: "5798",
    shortDescription: "LUMINAIRE:STREET LIGHT 400 W HPS CO SE",
    rate: "4437.18",
    unit: "EA",
    category: "Streetlight Luminaires",
  },
  {
    sapNumber: "5953",
    shortDescription: "TAPE PVC TYPE B RED",
    rate: "40.33",
    unit: "EA",
    category: "Insulating Tape",
  },
  {
    sapNumber: "6017",
    shortDescription: "TAPE PVC TYPE B GREEN",
    rate: "38.39",
    unit: "EA",
    category: "Insulating Tape",
  },
  {
    sapNumber: "6059",
    shortDescription: "TAPE PVC TYPE B BLACK",
    rate: "48.44",
    unit: "EA",
    category: "Insulating Tape",
  },
  {
    sapNumber: "6077",
    shortDescription: "LUG 95 CU CIR M12",
    rate: "185.6",
    unit: "EA",
    category: "Cable Lugs",
  },
  {
    sapNumber: "6081",
    shortDescription: "LUMINAIRE STREET LIGHT 250 W HPS CO SE",
    rate: "3323.54",
    unit: "EA",
    category: "Streetlight Luminaires",
  },
  {
    sapNumber: "6205",
    shortDescription: "FUSE LV 16A 80KA OFFSET TAG 58 MM LENGTH",
    rate: "147.49",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "6206",
    shortDescription: "FUSE LV 10A 80KA OFFSET TAG 58 MM LENGTH",
    rate: "139.32",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "6233",
    shortDescription: "Connector Screw No. 3",
    rate: "53.14",
    unit: "EA",
    category: "Electrical Accessories",
  },
  {
    sapNumber: "6234",
    shortDescription: "End Connector,Insulating Sleeve:No 3,PVC",
    rate: "54.31",
    unit: "EA",
    category: "Electrical Accessories",
  },
  {
    sapNumber: "6279",
    shortDescription: "PECU NEMA TYPE 1800VA FAIL ON",
    rate: "444.06",
    unit: "EA",
    category: "Luminaire Accessories",
  },
  {
    sapNumber: "6280",
    shortDescription: "PECU NEMA BASE",
    rate: "239.53",
    unit: "EA",
    category: "Luminaire Accessories",
  },
  {
    sapNumber: "6282",
    shortDescription: "Clamp U:Steel,16mm",
    rate: "116.66",
    unit: "EA",
    category: "Network Accessories",
  },
  {
    sapNumber: "6295",
    shortDescription: "PECU MICRO TYPE 1800VA FAIL ON",
    rate: "453.09",
    unit: "EA",
    category: "Luminaire Accessories",
  },
  {
    sapNumber: "6455",
    shortDescription: "FUSE LV 160A 80KA TYPE NH-00 DIST",
    rate: "206.77",
    unit: "EA",
    category: "Low Voltage Fuses",
  },
  {
    sapNumber: "6531",
    shortDescription: "SUSPENSION ASSEMBLY ABC",
    rate: "167.67",
    unit: "EA",
    category: "Network Accessories",
  },
  {
    sapNumber: "7190",
    shortDescription: "Lamp:400W,230V,TUB,E40,HPS",
    rate: "197.56",
    unit: "EA",
    category: "High Pressure Sodium Lamps",
  },
  {
    sapNumber: "7206",
    shortDescription: "Lamp:400W,230V,TUB,E40,MH",
    rate: "273.38",
    unit: "EA",
    category: "Metal Halide Lamps",
  },
  {
    sapNumber: "7235",
    shortDescription: "Lamp:70W,230V,Elliptical,E27,HPS",
    rate: "159.51",
    unit: "EA",
    category: "High Pressure Sodium Lamps",
  },
  {
    sapNumber: "7237",
    shortDescription: "Lamp:250W,230V,TUB,E40,HPS",
    rate: "194.18",
    unit: "EA",
    category: "High Pressure Sodium Lamps",
  },
  {
    sapNumber: "7258",
    shortDescription: "Lamp:100W,230V,Elliptical,E40,HPS",
    rate: "173.18",
    unit: "EA",
    category: "High Pressure Sodium Lamps",
  },
  {
    sapNumber: "7289",
    shortDescription: "ACSR MINK, 260A, 10.52MM DIAMETER",
    rate: "342.39",
    unit: "M",
    category: "Aluminium Conductor Steel Reinforced",
  },
  {
    sapNumber: "10786",
    shortDescription: "Strapping:20 X 0.7mm,S/S 304,Smooth",
    rate: "326.52",
    unit: "EA",
    category: "Network Accessories",
  },
  {
    sapNumber: "10787",
    shortDescription: "Buckle:20mm,S/S Grade 304,CP_TSSPEC_092",
    rate: "163.25",
    unit: "EA",
    category: "Network Accessories",
  },
];
